nelmio_api_doc:
    documentation:
        info:
            title: Symfony Skeleton 
            description: Symfony Framework version 5.1.11
            version: 1.0.0
        
        # 1) Define the security scheme type (HTTP bearer)
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    
        # 2) Apply the security globally to all operations
        # security:
        #     - Bearer: []

    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)